# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=release
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),release)
  tweb_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := tweb

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

tweb:
ifneq (,$(tweb_config))
	@echo "==== Building tweb ($(tweb_config)) ===="
	@${MAKE} --no-print-directory -C . -f tweb.make config=$(tweb_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f tweb.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tweb"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"